[versions]
# Gradle and Android
agp = "8.2.0"
kotlin = "1.9.22"
compileSdk = "34"
minSdk = "24"
targetSdk = "34"

# Kotlin
kotlinx-coroutines = "1.7.3"
kotlinx-serialization = "1.6.2"

# AndroidX
androidx-core-ktx = "1.12.0"

# Google
tink = "1.12.0"

# Testing
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
androidx-test-runner = "1.5.2"
androidx-test-rules = "1.5.0"
androidx-test-core = "1.5.0"

# Tools
dokka = "1.9.10"
ktlint = "11.6.1"
ktlintVersion = "1.0.1"
mavenPublish = "0.29.0"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Google Tink
tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tink" }

# AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

[bundles]
kotlin = [
    "kotlin-stdlib",
    "kotlinx-coroutines-android",
    "kotlinx-serialization-json",
]

test = [
    "junit",
    "kotlinx-coroutines-test",
]

android-test = [
    "androidx-test-ext-junit",
    "androidx-test-runner",
    "androidx-test-rules",
    "androidx-test-core",
    "kotlinx-coroutines-test",
    "kotlinx-serialization-json",
]

